//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 10:30:11 AM CEST 
//


package fr.univ_rouen.bd.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tomeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tomeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ-rouen.fr/bd}numero"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}informations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tomeType", propOrder = {
    "numero",
    "informations"
})
public class TomeType {

    protected float numero;
    @XmlElement(required = true)
    protected String informations;

    /**
     * Gets the value of the numero property.
     * 
     */
    public float getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     */
    public void setNumero(float value) {
        this.numero = value;
    }

    /**
     * Gets the value of the informations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformations() {
        return informations;
    }

    /**
     * Sets the value of the informations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformations(String value) {
        this.informations = value;
    }

}
