//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 10:30:11 AM CEST 
//
package fr.univ_rouen.bd.model.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ-rouen.fr/bd}id"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}insertedDate"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}titre"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}depotLegal"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}finImpression"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}parution"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}editeur"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}resume"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}format"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}creationDate"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}image"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}scenaristes"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}dessinateurs"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}coloristes"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}lettrages" minOccurs="0"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}encrages" minOccurs="0"/>
 *         &lt;element ref="{http://univ-rouen.fr/bd}tome" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://univ-rouen.fr/bd}isbn use="required""/>
 *       &lt;attribute ref="{http://univ-rouen.fr/bd}serie use="required""/>
 *       &lt;attribute ref="{http://univ-rouen.fr/bd}planches use="required""/>
 *       &lt;attribute ref="{http://univ-rouen.fr/bd}langue use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "insertedDate",
    "titre",
    "depotLegal",
    "finImpression",
    "parution",
    "editeur",
    "resume",
    "format",
    "creationDate",
    "image",
    "scenaristes",
    "dessinateurs",
    "coloristes",
    "lettrages",
    "encrages",
    "tome"
})
@XmlRootElement(name = "bd")
public class Bd {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar insertedDate;
    @XmlElement(required = true)
    protected String titre;
    @XmlElement(required = true)
    protected String depotLegal;
    @XmlElement(required = true)
    protected String finImpression;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar parution;
    @XmlElement(required = true)
    protected String editeur;
    @XmlElement(required = true)
    protected String resume;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String image;
    @XmlElement(required = true)
    protected ScenaristesType scenaristes;
    @XmlElement(required = true)
    protected DessinateursType dessinateurs;
    @XmlElement(required = true)
    protected ColoristesType coloristes;
    protected LettragesType lettrages;
    protected EncragesType encrages;
    protected TomeType tome;
    @XmlAttribute(name = "isbn", namespace = "http://univ-rouen.fr/bd", required = true)
    protected String isbn;
    @XmlAttribute(name = "serie", namespace = "http://univ-rouen.fr/bd", required = true)
    protected String serie;
    @XmlAttribute(name = "planches", namespace = "http://univ-rouen.fr/bd", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger planches;
    @XmlAttribute(name = "langue", namespace = "http://univ-rouen.fr/bd", required = true)
    protected String langue;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the insertedDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getInsertedDate() {
        return insertedDate;
    }

    /**
     * Sets the value of the insertedDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setInsertedDate(XMLGregorianCalendar value) {
        this.insertedDate = value;
    }

    /**
     * Gets the value of the titre property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTitre() {
        return titre;
    }

    /**
     * Sets the value of the titre property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTitre(String value) {
        this.titre = value;
    }

    /**
     * Gets the value of the depotLegal property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDepotLegal() {
        return depotLegal;
    }

    /**
     * Sets the value of the depotLegal property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDepotLegal(String value) {
        this.depotLegal = value;
    }

    /**
     * Gets the value of the finImpression property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFinImpression() {
        return finImpression;
    }

    /**
     * Sets the value of the finImpression property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFinImpression(String value) {
        this.finImpression = value;
    }

    /**
     * Gets the value of the parution property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getParution() {
        return parution;
    }

    /**
     * Sets the value of the parution property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setParution(XMLGregorianCalendar value) {
        this.parution = value;
    }

    /**
     * Gets the value of the editeur property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEditeur() {
        return editeur;
    }

    /**
     * Sets the value of the editeur property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEditeur(String value) {
        this.editeur = value;
    }

    /**
     * Gets the value of the resume property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getResume() {
        return resume;
    }

    /**
     * Sets the value of the resume property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setResume(String value) {
        this.resume = value;
    }

    /**
     * Gets the value of the format property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the image property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the scenaristes property.
     *
     * @return possible object is {@link ScenaristesType }
     *
     */
    public ScenaristesType getScenaristes() {
        return scenaristes;
    }

    /**
     * Sets the value of the scenaristes property.
     *
     * @param value allowed object is {@link ScenaristesType }
     *
     */
    public void setScenaristes(ScenaristesType value) {
        this.scenaristes = value;
    }

    /**
     * Gets the value of the dessinateurs property.
     *
     * @return possible object is {@link DessinateursType }
     *
     */
    public DessinateursType getDessinateurs() {
        return dessinateurs;
    }

    /**
     * Sets the value of the dessinateurs property.
     *
     * @param value allowed object is {@link DessinateursType }
     *
     */
    public void setDessinateurs(DessinateursType value) {
        this.dessinateurs = value;
    }

    /**
     * Gets the value of the coloristes property.
     *
     * @return possible object is {@link ColoristesType }
     *
     */
    public ColoristesType getColoristes() {
        return coloristes;
    }

    /**
     * Sets the value of the coloristes property.
     *
     * @param value allowed object is {@link ColoristesType }
     *
     */
    public void setColoristes(ColoristesType value) {
        this.coloristes = value;
    }

    /**
     * Gets the value of the lettrages property.
     *
     * @return possible object is {@link LettragesType }
     *
     */
    public LettragesType getLettrages() {
        return lettrages;
    }

    /**
     * Sets the value of the lettrages property.
     *
     * @param value allowed object is {@link LettragesType }
     *
     */
    public void setLettrages(LettragesType value) {
        this.lettrages = value;
    }

    /**
     * Gets the value of the encrages property.
     *
     * @return possible object is {@link EncragesType }
     *
     */
    public EncragesType getEncrages() {
        return encrages;
    }

    /**
     * Sets the value of the encrages property.
     *
     * @param value allowed object is {@link EncragesType }
     *
     */
    public void setEncrages(EncragesType value) {
        this.encrages = value;
    }

    /**
     * Gets the value of the tome property.
     *
     * @return possible object is {@link TomeType }
     *
     */
    public TomeType getTome() {
        return tome;
    }

    /**
     * Sets the value of the tome property.
     *
     * @param value allowed object is {@link TomeType }
     *
     */
    public void setTome(TomeType value) {
        this.tome = value;
    }

    /**
     * Gets the value of the isbn property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSerie() {
        if (serie == null) {
            return "One Shot";
        } else {
            return serie;
        }
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the planches property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPlanches() {
        return planches;
    }

    /**
     * Sets the value of the planches property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setPlanches(BigInteger value) {
        this.planches = value;
    }

    /**
     * Gets the value of the langue property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLangue() {
        return langue;
    }

    /**
     * Sets the value of the langue property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLangue(String value) {
        this.langue = value;
    }
}
