//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 10:30:11 AM CEST 
//


package fr.univ_rouen.bd.model.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.univ_rouen.bd.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Format_QNAME = new QName("http://univ-rouen.fr/bd", "format");
    private final static QName _Coloristes_QNAME = new QName("http://univ-rouen.fr/bd", "coloristes");
    private final static QName _Scenariste_QNAME = new QName("http://univ-rouen.fr/bd", "scenariste");
    private final static QName _Coloriste_QNAME = new QName("http://univ-rouen.fr/bd", "coloriste");
    private final static QName _Image_QNAME = new QName("http://univ-rouen.fr/bd", "image");
    private final static QName _Parution_QNAME = new QName("http://univ-rouen.fr/bd", "parution");
    private final static QName _Editeur_QNAME = new QName("http://univ-rouen.fr/bd", "editeur");
    private final static QName _Numero_QNAME = new QName("http://univ-rouen.fr/bd", "numero");
    private final static QName _Scenaristes_QNAME = new QName("http://univ-rouen.fr/bd", "scenaristes");
    private final static QName _Nom_QNAME = new QName("http://univ-rouen.fr/bd", "nom");
    private final static QName _Titre_QNAME = new QName("http://univ-rouen.fr/bd", "titre");
    private final static QName _Lettrages_QNAME = new QName("http://univ-rouen.fr/bd", "lettrages");
    private final static QName _InsertedDate_QNAME = new QName("http://univ-rouen.fr/bd", "insertedDate");
    private final static QName _Dessinateurs_QNAME = new QName("http://univ-rouen.fr/bd", "dessinateurs");
    private final static QName _FinImpression_QNAME = new QName("http://univ-rouen.fr/bd", "finImpression");
    private final static QName _Tome_QNAME = new QName("http://univ-rouen.fr/bd", "tome");
    private final static QName _DepotLegal_QNAME = new QName("http://univ-rouen.fr/bd", "depotLegal");
    private final static QName _Dessinateur_QNAME = new QName("http://univ-rouen.fr/bd", "dessinateur");
    private final static QName _Informations_QNAME = new QName("http://univ-rouen.fr/bd", "informations");
    private final static QName _Lettrage_QNAME = new QName("http://univ-rouen.fr/bd", "lettrage");
    private final static QName _Resume_QNAME = new QName("http://univ-rouen.fr/bd", "resume");
    private final static QName _CreationDate_QNAME = new QName("http://univ-rouen.fr/bd", "creationDate");
    private final static QName _Prenom_QNAME = new QName("http://univ-rouen.fr/bd", "prenom");
    private final static QName _Id_QNAME = new QName("http://univ-rouen.fr/bd", "id");
    private final static QName _Encrages_QNAME = new QName("http://univ-rouen.fr/bd", "encrages");
    private final static QName _Encrage_QNAME = new QName("http://univ-rouen.fr/bd", "encrage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.univ_rouen.bd.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TomeType }
     * 
     */
    public TomeType createTomeType() {
        return new TomeType();
    }

    /**
     * Create an instance of {@link DessinateursType }
     * 
     */
    public DessinateursType createDessinateursType() {
        return new DessinateursType();
    }

    /**
     * Create an instance of {@link IndividuType }
     * 
     */
    public IndividuType createIndividuType() {
        return new IndividuType();
    }

    /**
     * Create an instance of {@link ColoristesType }
     * 
     */
    public ColoristesType createColoristesType() {
        return new ColoristesType();
    }

    /**
     * Create an instance of {@link LettragesType }
     * 
     */
    public LettragesType createLettragesType() {
        return new LettragesType();
    }

    /**
     * Create an instance of {@link ScenaristesType }
     * 
     */
    public ScenaristesType createScenaristesType() {
        return new ScenaristesType();
    }

    /**
     * Create an instance of {@link EncragesType }
     * 
     */
    public EncragesType createEncragesType() {
        return new EncragesType();
    }

    /**
     * Create an instance of {@link Bd }
     * 
     */
    public Bd createBd() {
        return new Bd();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "format")
    public JAXBElement<String> createFormat(String value) {
        return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColoristesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "coloristes")
    public JAXBElement<ColoristesType> createColoristes(ColoristesType value) {
        return new JAXBElement<ColoristesType>(_Coloristes_QNAME, ColoristesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividuType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "scenariste")
    public JAXBElement<IndividuType> createScenariste(IndividuType value) {
        return new JAXBElement<IndividuType>(_Scenariste_QNAME, IndividuType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividuType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "coloriste")
    public JAXBElement<IndividuType> createColoriste(IndividuType value) {
        return new JAXBElement<IndividuType>(_Coloriste_QNAME, IndividuType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "image")
    public JAXBElement<String> createImage(String value) {
        return new JAXBElement<String>(_Image_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "parution")
    public JAXBElement<XMLGregorianCalendar> createParution(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Parution_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "editeur")
    public JAXBElement<String> createEditeur(String value) {
        return new JAXBElement<String>(_Editeur_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "numero")
    public JAXBElement<Float> createNumero(Float value) {
        return new JAXBElement<Float>(_Numero_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScenaristesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "scenaristes")
    public JAXBElement<ScenaristesType> createScenaristes(ScenaristesType value) {
        return new JAXBElement<ScenaristesType>(_Scenaristes_QNAME, ScenaristesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "nom")
    public JAXBElement<String> createNom(String value) {
        return new JAXBElement<String>(_Nom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "titre")
    public JAXBElement<String> createTitre(String value) {
        return new JAXBElement<String>(_Titre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LettragesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "lettrages")
    public JAXBElement<LettragesType> createLettrages(LettragesType value) {
        return new JAXBElement<LettragesType>(_Lettrages_QNAME, LettragesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "insertedDate")
    public JAXBElement<XMLGregorianCalendar> createInsertedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InsertedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DessinateursType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "dessinateurs")
    public JAXBElement<DessinateursType> createDessinateurs(DessinateursType value) {
        return new JAXBElement<DessinateursType>(_Dessinateurs_QNAME, DessinateursType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "finImpression")
    public JAXBElement<String> createFinImpression(String value) {
        return new JAXBElement<String>(_FinImpression_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TomeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "tome")
    public JAXBElement<TomeType> createTome(TomeType value) {
        return new JAXBElement<TomeType>(_Tome_QNAME, TomeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "depotLegal")
    public JAXBElement<String> createDepotLegal(String value) {
        return new JAXBElement<String>(_DepotLegal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividuType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "dessinateur")
    public JAXBElement<IndividuType> createDessinateur(IndividuType value) {
        return new JAXBElement<IndividuType>(_Dessinateur_QNAME, IndividuType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "informations")
    public JAXBElement<String> createInformations(String value) {
        return new JAXBElement<String>(_Informations_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividuType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "lettrage")
    public JAXBElement<IndividuType> createLettrage(IndividuType value) {
        return new JAXBElement<IndividuType>(_Lettrage_QNAME, IndividuType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "resume")
    public JAXBElement<String> createResume(String value) {
        return new JAXBElement<String>(_Resume_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "creationDate")
    public JAXBElement<XMLGregorianCalendar> createCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "prenom")
    public JAXBElement<String> createPrenom(String value) {
        return new JAXBElement<String>(_Prenom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncragesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "encrages")
    public JAXBElement<EncragesType> createEncrages(EncragesType value) {
        return new JAXBElement<EncragesType>(_Encrages_QNAME, EncragesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividuType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ-rouen.fr/bd", name = "encrage")
    public JAXBElement<IndividuType> createEncrage(IndividuType value) {
        return new JAXBElement<IndividuType>(_Encrage_QNAME, IndividuType.class, null, value);
    }

}
