//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 10:30:11 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://univ-rouen.fr/bd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.univ_rouen.bd.model.beans;
